### PR TITLE
Add a sound subsystem allowing mixing of audio between applications

### PR DESCRIPTION
**Pull request by gerow**
Howdy,

This patch series creates a pseudo-unified sound subsystem. It doesn't do much fancy right now other than allowing multiple samples to mix. It rips out the interface already in place for the ac97 module, so I hope you weren't getting too attached to it. On the upside, the new interface is pretty much the same sans the ioctl to start playing.

There also is the issue that currently there isn't a good way to tell a sound driver to stop playing. It does trigger some unnecessary interrupts and cause some unnecessary processing, but that can probably be resolved with a change or two to the current interface between the driver and snd.

### CODE REVIEW

**Comment by klange** [comment]
This works fantastically. Merged rebased 64d771b4fa3c28e41613155652b1fd954e591d17

**Comment by klange** [comment]
I have the audio face working with Quake (which is fairly well tailored for spitting audio out to any sort of PCM sink), but with the caveat that the latency is horrendous. I think we should look at reducing our buffer size quite a bit - it's the unfortunate tradeoff between available buffers and lower latency, but if we want near-realtime audio, we need to do it.

**Comment by gerow** [comment]
Wow, that's awesome!

Yeah, the latency is pretty bad right now. Not as bad as before this change <https://github.com/gerow/toaruos/commit/2bafbd7fd41273118870370662649edb67ec3abd#diff-20f3d11da668ae1d793d86a2548de075R39> but still pretty bad.

I messed around with changing the buffer length in the ac97 driver to an even lower value, but I was getting some weird distortion, at least in qemu. I'm not sure what the issue is, but I've got a few ideas on how to resolve it.

**Comment by gerow** [comment]
But yeah, getting it down to around 40ms or less would probably be a good goal.

**Comment by klange** [comment]
[Here](https://www.youtube.com/watch?v=oqNbsTpzrvU) is terrible recorded-with-my-phone capture of Quake doing its thing.

**Comment by gerow** [comment]
Did the change you recently made improve the latency enough? With a buffer length of 0x1000 that comes out to 0x800 samples, which is (1/48000) * 2048 ~= 43ms of latency in theory, which should probably be acceptable.

**Comment by klange** [comment]
It wasn't as big of an improvement as I'd hoped.

I think we need to make some changes to how we're pull samples off the mixer before we reduce the mixer buffer size - I was running into some interesting issues with it.

**Comment by klange** [comment]
We have ~1.4 seconds of total buffer space (if I didn't screw up the math), which based on some experimentation seems to be exactly what our delay is, which indicates to me that my attempts to race the DMA controller are failing in such a way that we still end up with our samples out by the next cycle. I'm not entirely clear on what the DMA controller's prefetch strategy looks like, but I suspect that's where we're getting bitten. Ultimately, it doesn't matter how small our buffers are (I've gotten them down to mere dozens of samples - single-digit milliseconds - while maintaining fluid output) if we're not presenting what we have to the card as early in its read cycle as possible.

**Comment by klange** [comment]
Ahhh, I figured out what I did wrong.

**Comment by klange** [comment]
Okay, I've pushed a fix. We're at the point where I can't identify the delay I know mathematically must be there.

**Comment by klange** [comment]
In other news, I'm not very good at Quake, but that should be a separate issue report.

**Comment by gerow** [comment]
"We're at the point where I can't identify the delay I know mathematically must be there." Should I be parsing this as "I know there's a delay, but it's so small that I can't tell"? If so, awesome! If not, ehhh....

**Comment by klange** [comment]
Sorry for being obtuse; yes, that is exactly what I meant.

**Pull request closed without merging**
