### PR TITLE
Compacted and cleaned vasprintf

### PR DESCRIPTION
**Pull request by napnac**
I cleaned a bit the implementation of the kernel printf function (now it's more compact and easier to extend).

Hope this helps ! :)

### CODE REVIEW

**Comment by travisg** [comment]
My $.02: Combining the two base versions into one that can handle all bases makes the code it generates far less efficient, especially around those divides, since it can't optimize /10 or /16 into simple shifts and masks, in the 16 case.

Since the routine is static, it may be possible that the compiler will inline the different versions and optimize out the constant again, but without forcing it inline you can't really guarantee it.

OTOH, it's not like the potential speed/size savings will likely matter much for an inner routine on printf.

**Comment by napnac** [comment]
I didn't think of this technical aspect indeed, I was just browsing through the kernel code and wondered if I could compact this function.

I will totally understand if this pull request is not merged for the speed argument ;)

**Comment by travisg** [comment]
Yeah, no worries. Like I said, the speed argument probably doesn't matter much on the type of hardware this OS runs on, since x86s have a nice fast integer divide instruction. For embedded cpus without divide, this sort of thing can take a huge amount of time if the compiler can't optimize it by knowing what the divisors are ahead of time.

**Comment by napnac** [comment]
Good to know, thanks !

**Pull request closed without merging**
